[home]
name = "ğŸ  Home"
icon = "house"

[[pages]]
path = "pages/1_Flashcards.py"
name = "ğŸ§  Flashcards"
icon = "book"

[[pages]]
path = "pages/2_Statistics.py"
name = "ğŸ“Š Statistics"
icon = "bar-chart"

[[pages]]
path = "pages/3_Configuration.py"
name = "âš™ï¸ Configuration"
icon = "sliders"

[[pages]]
path = "pages/4_Login.py"
name = "ğŸ” Login"
icon = "log-in"

[[pages]]
path = "pages/5_Settings.py"
name = "ğŸ› ï¸ Settings"
icon = "settings"
